video_device: /dev/video2
framerate: 30.0
image_width: 640
image_height: 480

pixel_format: "yuyv"

exposure_auto: 1  # 1 = manual
exposure_absolute: 200

white_balance_temperature_auto: false
white_balance_temperature: 4000
